In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5])

In [3]:
a

array([1, 2, 3, 4, 5])

In [4]:
b = np.array([[1,2,3], [4,5,6]])

In [5]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
c = np.array([[[1,2,3], [4,5,6]],[[1,2,3], [4,5,6]]])
c

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [7]:
print(c.ndim)

3


In [8]:
d = np.array([[[[1,2,3], [4,5,6]],[[1,2,3], [4,5,6]]], [[[1,2,3], [4,5,6]],[[1,2,3], [4,5,6]]]])

In [9]:
print(d.ndim)

4


In [10]:
d

array([[[[1, 2, 3],
         [4, 5, 6]],

        [[1, 2, 3],
         [4, 5, 6]]],


       [[[1, 2, 3],
         [4, 5, 6]],

        [[1, 2, 3],
         [4, 5, 6]]]])

In [11]:
print(a.dtype)

int64


In [12]:
type(a)

numpy.ndarray

In [13]:
d.shape

(2, 2, 2, 3)

In [14]:
d.ndim

4

In [15]:
d.reshape(4,6)

array([[1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6]])

In [16]:
d.resize([4,6])

In [17]:
d

array([[1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6]])